### ISSUE TITLE
Separate vending operation code and web server on machine

### ISSUE THREAD

**Issue by narendasan** [acm-uiuc/SIGBot-2016-2017#13]
Can the code for operating the machine's arm be put into a separate library, instead of fiddling with Pi GPIO in route handlers, will let us throw away one or the other if we wish

**Comment by abrandemuehl** [comment]
It would probably be worth splitting this into the "hat code", since the designs for the "hat" are in the repo as well

(Hat is in quotes since we don't technically have a true hat)

**Comment by rauhul** [comment]
I dont know the standards for repo structure for a project like this. Would we have one repo for each component, i.e. iOS App, Pi hat, Pi code? How would you recommending splitting up the repo?

**Comment by narendasan** [comment]
For repo structure I would recommend a separate repo for each component like groot (tagging them all merch will allow you to filter the other repos out). Might let you separate development more. This issue was more referring to things like https://github.com/acm-uiuc/Merch/blob/master/rPi_code/app.py#L23 where you are directly modifying GPIO states from a webserver. I would prefer having some library managing this and in the web server route being able to make a function call like Merch.vend("D2")

**Comment by abrandemuehl** [comment]
We don't have to split it into separate repos, just make it so that the code for handling the gpio is done as library calls, instead of copy pasting it into the flask app

**Comment by abrandemuehl** [comment]
I'll take a look at doing that

**Comment by abrandemuehl** [comment]
I'm not sure the scope of the project is large enough to be worth separate repos

**Comment by narendasan** [comment]
@abrandemuehl I think the library is a higher priority, but I think it might be worth separating the parts out because as development proceeds, ios devs wont care about the hardware specs, and the groot guys wont care about the ios code and ultimately we want to be in a position where any particular component can be replaced without the rest of the system breaking so creating expected abstract APIs for each component will be important. I would say make a team for merch development (and a gitter channel so random people can walk in and contribute) and have a bunch of repos you manage. I can help set that up as I did the same for groot. @rauhul @abrandemuehl let me know if you want me to set that up.

**Comment by rauhul** [comment]
@narendasan yeah, you could set it up please.

**Comment by abrandemuehl** [comment]
Okay, sounds good

**Comment by narendasan** [comment]
Closing and moving issue about separation of GPIO code and webserver to https://github.com/acm-uiuc/merch-embedded
