### ISSUE TITLE
Explore getting machine state directly from control board 

### ISSUE THREAD

**Issue by rauhul** [acm-uiuc/SIGBot-2016-2017#17]
As the title suggests, we would like to find a way to know what the machine is currently doing from some pins exported from the control board.

**Comment by narendasan** [comment]
Or some sort of diagnostic system (e.g. LEDs)

**Comment by pwk2** [comment]
Most relevent/potentially helpful thing to tracking the machine state I found were P3 P4 switches which hold the information of if the Picker is HOME/OUT, respectively. I believe this to be the way the vending machine controls machine state.
<img width="335" alt="picker" src="https://user-images.githubusercontent.com/23651383/30304376-cb5cf75a-9732-11e7-895a-f1837dd8f5a0.png">

**Comment by pwk2** [comment]
After hours or reading and searching, xy limit seem to be the way to go.
